### ISSUE TITLE
What does --template mean?

### ISSUE THREAD

**Issue by yuvaldolev** [Stanford-Mobisocial-IoT-Lab/genie-toolkit#18]
Hi,
In your example for generating synthetic set you passed ```--template template.genie``` to the generate command. What is the template flag? I'm finding it hard to figure out what needs to be in the template.genie file.

When I used the  --help flag I got the following output:
```--template TEMPLATE   Path to file containing construct templates, in Genie syntax.```,
but I still didn't understand what the template flag means. Do I need to create the file myself and if so what does it need to contain, or can it be generated automatically?

Thanks!

**Comment by gcampax** [comment]
The template file is the main input to Genie: it describes both the set of sentences that you wish to generate automatically to train on, and their corresponding programs.
For English -> ThingTalk (the only code generation problem fully supported so far), the main template file lives in `languages/en/thingtalk.genie`, so you can invoke `generate` as:
```
genie generate --template languages/en/thingtalk.genie --locale en-US --thingpedia thingpedia.json --dataset dataset.tt -o synthetic.tsv
```

**Comment by yuvaldolev** [comment]
OK,
Thank you!
