### ISSUE TITLE
Cannot download the dataset.

### ISSUE THREAD

**Issue by whwang299** [Stanford-Mobisocial-IoT-Lab/genie-toolkit#21]
Hi all.

Thanks for the interesting work.
The link " https://oval.cs.stanford.edu/datasets/pldi2019-quote-free.zip" doesn't seem to work.

Thanks!

**Comment by gcampax** [comment]
Thank you, the correct link is https://oval.cs.stanford.edu/datasets/pldi19-quote-free.zip
I fixed the instructions.
