### ISSUE TITLE
Typos in Thingpedia Dataset

### ISSUE THREAD

**Issue by elvisyjlin** [Stanford-Mobisocial-IoT-Lab/genie-toolkit#25]
I grabbed the TT dataset by
```bash
genie download-dataset -o dataset.tt
```

Found a typo in it:

* action  := @com.imgur.upload(to_gallery=false, picture_url=$undefined, title=$undefined)
  "upload a orivate picture to Imgur" should be "upload a private picture to Imgur"

**Comment by gcampax** [comment]
Thanks, fixed.
